sudo: false
language: node_js

node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" = "0.6" ] && npm conf set strict-ssl false || true'
  - '[ "${TRAVIS_NODE_VERSION}" = "0.6" ] && npm install -g npm@~1.4.0 || true'
  - '[ "${TRAVIS_NODE_VERSION}" = "0.8" ] && npm install -g npm@~1.4.0 || true'
